const Card = [
    {
        id: "0",
        img: "images1.jpg",
        imgAlt: "Xtreme",
        title: "Xtreme Motorbikes",
        caption: "With elements of adventure and survival",
        date: "14.07.2021"
    },
    {
        id: "1",
        img: "images2.jpg",
        imgAlt: "Evo-F",
        title: "Evo-F",
        caption: "One of the most iconic series of racing simulations",
        date: "12.07.2021",
    },
    {
        id: "2",
        img: "images3.jpg",
        imgAlt: "Next Drive",
        title: "Next Drive",
        caption: "Surprisingly good character customization tool",
        date: "01.07.2021",
    },
    {
        id: "3",
        img: "images4.jpg",
        imgAlt: "Evo-F3",
        title: "Evo-F3",
        caption: "It's an FPS with all kinds of game modes including battle royale",
        date: "29.07.2021",
    },
    {
        id: "4",
        img: "images5.jpg",
        imgAlt: "Scrap",
        title: "Scrap Metal 4",
        caption: "One of the best shooters on google play",
        date: "21.07.2021",
    },
    {
        id: "5",
        img: "images6.jpg",
        imgAlt: "Derby",
        title: "Derby Crash 2",
        caption: "Is an RPG from the creators of The Elder Scrolls series",
        date: "22.07.2021",
    },
    {
        id: "6",
        img: "images7.jpg",
        imgAlt: "SplatPed",
        title: "SplatPed",
        caption: "One of the newest racing games on android",
        date: "17.07.2021",
    },
    {
        id: "7",
        img: "images8.jpg",
        imgAlt: "Monster",
        title: "Monster Smash Cars",
        caption: "Puzzle game from Noodlecake Studios and State of Play Games",
        date: "8.07.2021",
    },
    {
        id: "8",
        img: "images9.jpg",
        imgAlt: "Scrap",
        title: "Scrap Metal 6",
        caption: "Each 10-minute game takes you to a remote island where you fight",
        date: "19.07.2021",
    },
    {
        id: "9",
        img: "images10.jpg",
        imgAlt: "Flying",
        title: "Flying Mech Robot",
        caption: "Is a ported version of the popular Nintendo 3DS game",
        date: "24.07.2021",
    },
    {
        id: "10",
        img: "images11.jpg",
        imgAlt: "War",
        title: "War Hero Iron",
        caption: "This is one of the best puzzle games available and also an incredibly great ",
        date: "30.07.2021",
    },
    {
        id: "11",
        img: "images12.jpg",
        imgAlt: "Metaverse",
        title: "Metaverse",
        caption: "A Network of 3D virtual worlds focused on social connection.",
        date: "1.07.2021",
    }
]
const client = [
    {
        id: "user1",
        description: "I know in real-time where the money is spent,and I don’t have to lend out the company’s credit card anymore. What a relief!",
        img: "Ellipse 11.png",
        imgAlt: "fhotouser1",
        name: "Denny Hilguston",
        address: "@denny.hill",  
    },
    {
        id: "user2",
        description: "VISUALS are much better. The improvements in optics and resolution and much more than a modern console generation leap.",
        img: "Ellipse 11 (1).png",
        imgAlt: "fhotouser2",
        name: "Vani Pandey",
        address: "@vani.pandey",  
    },
    {
        id: "user3",
        description: "I can actually see the improvement in the graphics, not having the external sensors is a big plus.",
        img: "Ellipse 11 (3).png",
        imgAlt: "fhotouser3",
        name: "milly Singh",
        address: "@milly.singh",  
    }
]